### ISSUE TITLE
Problem with matching notice headers because of line endings mismatch on Windows

### ISSUE THREAD

**Issue by OrkoHunter** [nickdeis/eslint-plugin-notice#11]
Hi @nickdeis ! Thank you for creating the tool, it's very useful! ❤️ 

Friends at Spotify are using this plugin to lint for notice headers in their Open Source projects. See [spotify/eslint-config-oss](https://github.com/spotify/eslint-config-oss). There is a [notice template file](https://github.com/spotify/eslint-config-oss/blob/master/notice-template.txt) in the repository containing the template for Spotify copyright notice.

When working on [spotify/backstage](https://github.com/spotify/backstage), users noticed that the project would not build on Windows OS and the problem is "missing notice header". Note that there are no errors on the unix platform. All the project source files do have the notice in place, and we should not be seeing this error.
Another key fact is that our build broke when we moved the notice header to a separate text file.

One of the causes we think is that the line endings are different in the backstage source code files and the `notice-template.txt`. And thus, the matching logic in `eslint-plugin-notice` is having issues, even though the notice text is exactly the same.

I am referring [this comment](https://github.com/spotify/backstage/issues/613#issuecomment-619642960) from @Rugvip on https://github.com/spotify/backstage/issues/613. The issue has more details!

A possible solution is to improve the logic in this plugin to ignore line endings when matching the notice headers. Or it could allow to suppress errors raised due to line endings.

Let us know your thoughts! 🙇 

cc @fastfrwrd

**Comment by nickdeis** [comment]
Hey @OrkoHunter,
Thank you for the incredibly kind words and the detailed defect ticket. This seems like a change to the eslint plugin API, because I also ran into this problem while updating unit tests during a routine security update that included updating to eslint 6 to perform tests. 

> A possible solution is to improve the logic in this plugin to ignore line endings when matching the notice headers. 

This is an excellent solution. Or at least normalize line endings to be unix line endings. I don't think people care too much about what kind of line endings are in a copyright notice, but maybe their existence matters.

I'll look into fixing this soon (today probably) as well as adding a CI system to test on both windows/mac. I think Travis CI supports that.
Best,
Nick

**Comment by nickdeis** [comment]
Hey @OrkoHunter,
I have committed a fix for the problem and added a CI file, as well as add "staging" like tests. I have published a package `@0.9.10`. Please let me know how this works out. Given the platform specific nature of this defect, I will keep this issue open until I get confirmation from you that it's working for your users.
Best,
Nick

**Comment by OrkoHunter** [comment]
Thank you thank you @nickdeis !!

**Comment by OrkoHunter** [comment]
Thank you @nickdeis ! This looks fixed, and I will close the issue.
